"""empty message

Revision ID: 3f26eea1fc79
Revises: None
Create Date: 2015-04-09 11:35:27.199979

"""

# revision identifiers, used by Alembic.
revision = '3f26eea1fc79'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
